name: firestore_collection
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: 0.14.2
  sorted_list: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: